//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.ModeloMapeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int CitaId { get; set; }
        public Nullable<int> PacienteId { get; set; }
        public string Antecedentes { get; set; }
        public string Recomendaciones { get; set; }
        public Nullable<int> EstadoCita { get; set; }
        public Nullable<int> Calificacion { get; set; }
        public Nullable<long> SesionId { get; set; }
    
        public virtual Paciente Paciente { get; set; }
        public virtual Sesion Sesion { get; set; }
    }
}
