//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modelo.ModeloMapeo
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfertaHorario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OfertaHorario()
        {
            this.Sesion = new HashSet<Sesion>();
        }
    
        public int OfertaHorarioId { get; set; }
        public Nullable<System.DateTime> Dia { get; set; }
        public Nullable<int> HoraInicio { get; set; }
        public Nullable<int> HoraFin { get; set; }
        public Nullable<int> UsuarioId { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sesion> Sesion { get; set; }
    }
}
